// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNaju1oHW269MmfZgmFVX1Z2B5msHIAo',
    appId: '1:648817884559:web:65b378fd8dda8ce0cb1ffa',
    messagingSenderId: '648817884559',
    projectId: 'excelerate-xlr8',
    authDomain: 'excelerate-xlr8.firebaseapp.com',
    storageBucket: 'excelerate-xlr8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboeMhEhsazLkH6HWbizWgsIETPypEd-s',
    appId: '1:648817884559:android:b1acec703173eaa4cb1ffa',
    messagingSenderId: '648817884559',
    projectId: 'excelerate-xlr8',
    storageBucket: 'excelerate-xlr8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl_KOcqqEVojZ83uiDSM0Z4qI6VAw9O98',
    appId: '1:648817884559:ios:9db24cb8f30e7c56cb1ffa',
    messagingSenderId: '648817884559',
    projectId: 'excelerate-xlr8',
    storageBucket: 'excelerate-xlr8.firebasestorage.app',
    iosBundleId: 'com.example.excelerate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl_KOcqqEVojZ83uiDSM0Z4qI6VAw9O98',
    appId: '1:648817884559:ios:9db24cb8f30e7c56cb1ffa',
    messagingSenderId: '648817884559',
    projectId: 'excelerate-xlr8',
    storageBucket: 'excelerate-xlr8.firebasestorage.app',
    iosBundleId: 'com.example.excelerate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNaju1oHW269MmfZgmFVX1Z2B5msHIAo',
    appId: '1:648817884559:web:e0d3b7c33d2cff72cb1ffa',
    messagingSenderId: '648817884559',
    projectId: 'excelerate-xlr8',
    authDomain: 'excelerate-xlr8.firebaseapp.com',
    storageBucket: 'excelerate-xlr8.firebasestorage.app',
  );
}
