// lib/mock_courses.dart
import 'models/courseModel.dart';

final List<String> categories = [
  'All',
  'Web Development',
  'Design',
  'Mobile Development',
  'Data Science',
];

// Helper mock lesson generator
List<Map<String, String>> mockLessons(String topic) {
  return List.generate(
    8,
    (index) => {
      'title': '$topic Lesson ${index + 1}',
      'duration': '${10 + index} mins',
      'status': index < 3
          ? 'Completed'
          : index == 3
              ? 'In Progress'
              : 'Locked',
    },
  );
}

final List<Course> allCourses = [
  // 🌐 WEB DEVELOPMENT (10)
  Course(
    title: 'Advanced React & Typescript',
    category: 'Web Development',
    lessons: 12,
    rating: 4.8,
    progress: 0.45,
    icon: '💻',
    status: 'In Progress',
    instructor: 'Alex Johnson',
    role: 'Senior Frontend Engineer',
    numStudents: 2400,
    totalTime: 18,
    reviews: 320,
    description:
        'Master React 18 and TypeScript for building robust, scalable web applications with confidence.',
    lessonsList: mockLessons('React & TypeScript'),
    students: 2100,
    duration: 18,
  ),
  Course(
    title: 'Node.js API Development',
    category: 'Web Development',
    lessons: 18,
    rating: 4.7,
    progress: 0.3,
    icon: '🧠',
    status: 'Saved',
    instructor: 'James Miller',
    role: 'Backend Developer',
    numStudents: 1800,
    totalTime: 15,
    reviews: 250,
    description:
        'Build production-ready REST APIs using Node.js, Express, and MongoDB.',
    lessonsList: mockLessons('Node.js API'),
    students: 1750,
    duration: 16,
  ),
  Course(
    title: 'Mastering HTML, CSS & JS',
    category: 'Web Development',
    lessons: 25,
    rating: 4.9,
    progress: 0.9,
    icon: '🌐',
    status: 'Completed',
    instructor: 'Linda White',
    role: 'UI Developer',
    numStudents: 5600,
    totalTime: 22,
    reviews: 410,
    description:
        'The ultimate front-end foundation course to master HTML, CSS, and JavaScript from scratch.',
    lessonsList: mockLessons('Frontend Basics'),
    students: 5200,
    duration: 22,
  ),
  Course(
    title: 'Next.js Fullstack Guide',
    category: 'Web Development',
    lessons: 20,
    rating: 4.8,
    progress: 0.6,
    icon: '⚛️',
    status: 'In Progress',
    instructor: 'David Lee',
    role: 'Fullstack Engineer',
    numStudents: 2200,
    totalTime: 20,
    reviews: 310,
    description:
        'Build scalable and fast fullstack apps using Next.js, React, and APIs.',
    lessonsList: mockLessons('Next.js'),
    students: 2100,
    duration: 20,
  ),
  Course(
    title: 'Building RESTful APIs with Express',
    category: 'Web Development',
    lessons: 14,
    rating: 4.6,
    progress: 0.2,
    icon: '🧩',
    status: 'Not Started',
    instructor: 'Emma Brown',
    role: 'Software Engineer',
    numStudents: 1300,
    totalTime: 10,
    reviews: 190,
    description:
        'Learn how to create powerful RESTful APIs using Express and integrate with modern frontends.',
    lessonsList: mockLessons('Express API'),
    students: 1250,
    duration: 10,
  ),
  Course(
    title: 'Tailwind CSS Deep Dive',
    category: 'Web Development',
    lessons: 10,
    rating: 4.7,
    progress: 0.8,
    icon: '💠',
    status: 'Completed',
    instructor: 'Sophia Green',
    role: 'Frontend Designer',
    numStudents: 800,
    totalTime: 6,
    reviews: 120,
    description:
        'Unlock the full potential of Tailwind CSS for responsive and elegant UI development.',
    lessonsList: mockLessons('Tailwind CSS'),
    students: 750,
    duration: 6,
  ),
  Course(
    title: 'Vue.js 3 Masterclass',
    category: 'Web Development',
    lessons: 22,
    rating: 4.9,
    progress: 0.5,
    icon: '🖥️',
    status: 'In Progress',
    instructor: 'Lucas Turner',
    role: 'Frontend Engineer',
    numStudents: 1700,
    totalTime: 17,
    reviews: 300,
    description:
        'Master Vue.js 3 with Composition API, state management, and scalable component design.',
    lessonsList: mockLessons('Vue.js'),
    students: 1650,
    duration: 17,
  ),
  Course(
    title: 'GraphQL & Apollo Fundamentals',
    category: 'Web Development',
    lessons: 15,
    rating: 4.7,
    progress: 0.4,
    icon: '🔗',
    status: 'Saved',
    instructor: 'Olivia Martin',
    role: 'Software Architect',
    numStudents: 1500,
    totalTime: 13,
    reviews: 210,
    description:
        'Learn how to design and consume GraphQL APIs using Apollo Client and Server.',
    lessonsList: mockLessons('GraphQL'),
    students: 1450,
    duration: 13,
  ),
  Course(
    title: 'Web Accessibility (A11Y) Essentials',
    category: 'Web Development',
    lessons: 8,
    rating: 4.8,
    progress: 0.3,
    icon: '♿',
    status: 'Not Started',
    instructor: 'Noah Wright',
    role: 'Accessibility Advocate',
    numStudents: 500,
    totalTime: 5,
    reviews: 75,
    description:
        'Ensure your websites are accessible to all users by mastering A11Y best practices.',
    lessonsList: mockLessons('Accessibility'),
    students: 480,
    duration: 5,
  ),
  Course(
    title: 'SEO Optimization for Developers',
    category: 'Web Development',
    lessons: 9,
    rating: 4.5,
    progress: 0.2,
    icon: '🚀',
    status: 'Saved',
    instructor: 'Mia Carter',
    role: 'Digital Marketer',
    numStudents: 950,
    totalTime: 8,
    reviews: 160,
    description:
        'Improve your website visibility and performance with developer-focused SEO techniques.',
    lessonsList: mockLessons('SEO'),
    students: 900,
    duration: 8,
  ),

  // 🎨 DESIGN (10)
  Course(
    title: 'UI/UX Design Fundamentals',
    category: 'Design',
    lessons: 15,
    rating: 4.9,
    progress: 0.7,
    icon: '🎨',
    status: 'In Progress',
    instructor: 'Chloe Kim',
    role: 'Product Designer',
    numStudents: 2100,
    totalTime: 14,
    reviews: 270,
    description:
        'Learn the principles of user interface and experience design with hands-on Figma projects.',
    lessonsList: mockLessons('UI/UX'),
    students: 2050,
    duration: 14,
  ),
  Course(
    title: 'Figma for Beginners',
    category: 'Design',
    lessons: 10,
    rating: 4.6,
    progress: 0.3,
    icon: '🖌️',
    status: 'Saved',
    instructor: 'Ethan Hall',
    role: 'Visual Designer',
    numStudents: 1300,
    totalTime: 8,
    reviews: 180,
    description:
        'Get started with Figma and learn how to create beautiful, responsive UI designs.',
    lessonsList: mockLessons('Figma'),
    students: 1200,
    duration: 8,
  ),
  Course(
    title: 'Design Systems in Practice',
    category: 'Design',
    lessons: 12,
    rating: 4.8,
    progress: 0.4,
    icon: '🧱',
    status: 'In Progress',
    instructor: 'Isabella Brown',
    role: 'Design System Lead',
    numStudents: 950,
    totalTime: 10,
    reviews: 150,
    description:
        'Build scalable and consistent design systems for modern web and mobile applications.',
    lessonsList: mockLessons('Design Systems'),
    students: 920,
    duration: 10,
  ),
  Course(
    title: 'Color Theory & Composition',
    category: 'Design',
    lessons: 8,
    rating: 4.5,
    progress: 0.2,
    icon: '🎨',
    status: 'Not Started',
    instructor: 'Henry Collins',
    role: 'Creative Director',
    numStudents: 600,
    totalTime: 5,
    reviews: 90,
    description:
        'Master the use of color, contrast, and visual hierarchy to create stunning designs.',
    lessonsList: mockLessons('Color Theory'),
    students: 550,
    duration: 5,
  ),
  Course(
    title: 'Typography Masterclass',
    category: 'Design',
    lessons: 10,
    rating: 4.7,
    progress: 0.5,
    icon: '🔤',
    status: 'In Progress',
    instructor: 'Grace Allen',
    role: 'Graphic Designer',
    numStudents: 700,
    totalTime: 6,
    reviews: 100,
    description:
        'Learn typography principles and best practices to elevate your design layouts.',
    lessonsList: mockLessons('Typography'),
    students: 680,
    duration: 6,
  ),
  Course(
    title: 'Wireframing & Prototyping in Figma',
    category: 'Design',
    lessons: 14,
    rating: 4.8,
    progress: 0.6,
    icon: '🧩',
    status: 'Completed',
    instructor: 'Daniel Young',
    role: 'Product Designer',
    numStudents: 1100,
    totalTime: 12,
    reviews: 190,
    description:
        'Learn to quickly wireframe and prototype with Figma for collaborative design projects.',
    lessonsList: mockLessons('Prototyping'),
    students: 1080,
    duration: 12,
  ),
  Course(
    title: 'Designing for Mobile Interfaces',
    category: 'Design',
    lessons: 12,
    rating: 4.7,
    progress: 0.4,
    icon: '📱',
    status: 'In Progress',
    instructor: 'Ella Roberts',
    role: 'UI Designer',
    numStudents: 890,
    totalTime: 9,
    reviews: 130,
    description:
        'Optimize your designs for mobile experiences using responsive and adaptive layouts.',
    lessonsList: mockLessons('Mobile Design'),
    students: 870,
    duration: 9,
  ),
  Course(
    title: 'UX Research & Testing',
    category: 'Design',
    lessons: 11,
    rating: 4.9,
    progress: 0.8,
    icon: '🔍',
    status: 'Completed',
    instructor: 'Liam Scott',
    role: 'UX Researcher',
    numStudents: 1300,
    totalTime: 10,
    reviews: 200,
    description:
        'Master user research, interviews, and usability testing for informed design decisions.',
    lessonsList: mockLessons('UX Research'),
    students: 1250,
    duration: 10,
  ),
  Course(
    title: 'Design Portfolio Building',
    category: 'Design',
    lessons: 9,
    rating: 4.6,
    progress: 0.3,
    icon: '📁',
    status: 'Saved',
    instructor: 'Zoe Walker',
    role: 'Art Director',
    numStudents: 750,
    totalTime: 7,
    reviews: 100,
    description:
        'Create a stunning design portfolio that highlights your strengths and attracts employers.',
    lessonsList: mockLessons('Portfolio'),
    students: 740,
    duration: 7,
  ),
  Course(
    title: 'Advanced UI Animations',
    category: 'Design',
    lessons: 13,
    rating: 4.8,
    progress: 0.5,
    icon: '🎞️',
    status: 'In Progress',
    instructor: 'Noah Brooks',
    role: 'Motion Designer',
    numStudents: 1020,
    totalTime: 11,
    reviews: 160,
    description:
        'Add delightful motion and transitions to your interfaces using Figma and After Effects.',
    lessonsList: mockLessons('Animations'),
    students: 980,
    duration: 11,
  ),
];
