// lib/mock_courses.dart

final List<String> categories = [
  'All',
  'Web Development',
  'Design',
  'Mobile Development',
  'Data Science',
];

final List<Map<String, dynamic>> allCourses = [
  // 🌐 WEB DEVELOPMENT (10)
  {
    'title': 'Advanced React & Typescript',
    'category': 'Web Development',
    'lessons': 12,
    'rating': 4.8,
    'progress': 0.45,
    'icon': '💻',
  },
  {
    'title': 'Node.js API Development',
    'category': 'Web Development',
    'lessons': 18,
    'rating': 4.7,
    'progress': 0.3,
    'icon': '🧠',
  },
  {
    'title': 'Mastering HTML, CSS & JS',
    'category': 'Web Development',
    'lessons': 25,
    'rating': 4.9,
    'progress': 0.9,
    'icon': '🌐',
  },
  {
    'title': 'Next.js Fullstack Guide',
    'category': 'Web Development',
    'lessons': 20,
    'rating': 4.8,
    'progress': 0.6,
    'icon': '⚛️',
  },
  {
    'title': 'Building RESTful APIs with Express',
    'category': 'Web Development',
    'lessons': 14,
    'rating': 4.6,
    'progress': 0.2,
    'icon': '🧩',
  },
  {
    'title': 'Tailwind CSS Deep Dive',
    'category': 'Web Development',
    'lessons': 10,
    'rating': 4.7,
    'progress': 0.8,
    'icon': '💠',
  },
  {
    'title': 'Vue.js 3 Masterclass',
    'category': 'Web Development',
    'lessons': 22,
    'rating': 4.9,
    'progress': 0.5,
    'icon': '🖥️',
  },
  {
    'title': 'GraphQL & Apollo Fundamentals',
    'category': 'Web Development',
    'lessons': 15,
    'rating': 4.7,
    'progress': 0.4,
    'icon': '🔗',
  },
  {
    'title': 'Web Accessibility (A11Y) Essentials',
    'category': 'Web Development',
    'lessons': 8,
    'rating': 4.8,
    'progress': 0.3,
    'icon': '♿',
  },
  {
    'title': 'SEO Optimization for Developers',
    'category': 'Web Development',
    'lessons': 9,
    'rating': 4.5,
    'progress': 0.2,
    'icon': '🚀',
  },

  // 🎨 DESIGN (10)
  {
    'title': 'UI/UX Design Fundamentals',
    'category': 'Design',
    'lessons': 15,
    'rating': 4.9,
    'progress': 0.7,
    'icon': '🎨',
  },
  {
    'title': 'Figma for Beginners',
    'category': 'Design',
    'lessons': 10,
    'rating': 4.6,
    'progress': 0.3,
    'icon': '🖌️',
  },
  {
    'title': 'Design Systems Mastery',
    'category': 'Design',
    'lessons': 20,
    'rating': 4.8,
    'progress': 0.6,
    'icon': '📐',
  },
  {
    'title': 'Prototyping with Figma & Adobe XD',
    'category': 'Design',
    'lessons': 14,
    'rating': 4.7,
    'progress': 0.4,
    'icon': '🧩',
  },
  {
    'title': 'Typography Essentials',
    'category': 'Design',
    'lessons': 8,
    'rating': 4.6,
    'progress': 0.2,
    'icon': '🔤',
  },
  {
    'title': 'Color Theory for Designers',
    'category': 'Design',
    'lessons': 6,
    'rating': 4.7,
    'progress': 0.5,
    'icon': '🌈',
  },
  {
    'title': 'Product Design for Startups',
    'category': 'Design',
    'lessons': 18,
    'rating': 4.9,
    'progress': 0.4,
    'icon': '🚀',
  },
  {
    'title': 'Creative Direction & Branding',
    'category': 'Design',
    'lessons': 12,
    'rating': 4.8,
    'progress': 0.6,
    'icon': '✨',
  },
  {
    'title': 'Design Thinking Workshop',
    'category': 'Design',
    'lessons': 16,
    'rating': 4.9,
    'progress': 0.3,
    'icon': '💡',
  },
  {
    'title': 'Animation & Motion Graphics',
    'category': 'Design',
    'lessons': 20,
    'rating': 4.8,
    'progress': 0.5,
    'icon': '🎞️',
  },

  // 📱 MOBILE DEVELOPMENT (10)
  {
    'title': 'Flutter & Dart Masterclass',
    'category': 'Mobile Development',
    'lessons': 20,
    'rating': 4.7,
    'progress': 0.2,
    'icon': '📱',
  },
  {
    'title': 'Android Jetpack Compose',
    'category': 'Mobile Development',
    'lessons': 18,
    'rating': 4.8,
    'progress': 0.5,
    'icon': '🤖',
  },
  {
    'title': 'SwiftUI for iOS Developers',
    'category': 'Mobile Development',
    'lessons': 16,
    'rating': 4.9,
    'progress': 0.8,
    'icon': '🍎',
  },
  {
    'title': 'Kotlin for Android Beginners',
    'category': 'Mobile Development',
    'lessons': 14,
    'rating': 4.6,
    'progress': 0.4,
    'icon': '📲',
  },
  {
    'title': 'React Native Bootcamp',
    'category': 'Mobile Development',
    'lessons': 22,
    'rating': 4.8,
    'progress': 0.3,
    'icon': '⚛️',
  },
  {
    'title': 'Mobile UI Design with Flutter',
    'category': 'Mobile Development',
    'lessons': 12,
    'rating': 4.7,
    'progress': 0.6,
    'icon': '🎨',
  },
  {
    'title': 'Integrating Firebase in Flutter',
    'category': 'Mobile Development',
    'lessons': 15,
    'rating': 4.9,
    'progress': 0.4,
    'icon': '🔥',
  },
  {
    'title': 'Performance Optimization in Android',
    'category': 'Mobile Development',
    'lessons': 10,
    'rating': 4.7,
    'progress': 0.2,
    'icon': '⚙️',
  },
  {
    'title': 'iOS App Architecture Patterns',
    'category': 'Mobile Development',
    'lessons': 11,
    'rating': 4.8,
    'progress': 0.5,
    'icon': '🏗️',
  },
  {
    'title': 'Publishing Apps to Stores',
    'category': 'Mobile Development',
    'lessons': 8,
    'rating': 4.6,
    'progress': 0.3,
    'icon': '🛒',
  },

  // 📊 DATA SCIENCE (10)
  {
    'title': 'Python for Data Analysis',
    'category': 'Data Science',
    'lessons': 22,
    'rating': 4.9,
    'progress': 0.4,
    'icon': '🐍',
  },
  {
    'title': 'Machine Learning with TensorFlow',
    'category': 'Data Science',
    'lessons': 30,
    'rating': 4.8,
    'progress': 0.6,
    'icon': '🤖',
  },
  {
    'title': 'Data Visualization with Power BI',
    'category': 'Data Science',
    'lessons': 12,
    'rating': 4.7,
    'progress': 0.3,
    'icon': '📊',
  },
  {
    'title': 'Deep Learning with PyTorch',
    'category': 'Data Science',
    'lessons': 25,
    'rating': 4.8,
    'progress': 0.5,
    'icon': '🧠',
  },
  {
    'title': 'Statistics for Data Science',
    'category': 'Data Science',
    'lessons': 18,
    'rating': 4.7,
    'progress': 0.2,
    'icon': '📈',
  },
  {
    'title': 'Data Cleaning with Pandas',
    'category': 'Data Science',
    'lessons': 10,
    'rating': 4.6,
    'progress': 0.4,
    'icon': '🧹',
  },
  {
    'title': 'SQL for Analysts',
    'category': 'Data Science',
    'lessons': 16,
    'rating': 4.8,
    'progress': 0.3,
    'icon': '🗃️',
  },
  {
    'title': 'Time Series Forecasting',
    'category': 'Data Science',
    'lessons': 14,
    'rating': 4.9,
    'progress': 0.5,
    'icon': '⏱️',
  },
  {
    'title': 'AI Ethics & Responsible ML',
    'category': 'Data Science',
    'lessons': 8,
    'rating': 4.7,
    'progress': 0.1,
    'icon': '⚖️',
  },
  {
    'title': 'Big Data with Spark',
    'category': 'Data Science',
    'lessons': 28,
    'rating': 4.8,
    'progress': 0.7,
    'icon': '💾',
  },
];