// lib/mock_courses.dart
import 'models/course_model.dart';

// Categories (same as before)
final List<String> categories = [
  'All',
  'Web Development',
  'Design',
  'Mobile Development',
  'Data Science',
];

// Helper to generate lessons with Locked status initially
List<Map<String, dynamic>> mockLessons(String topic, [int count = 8]) {
  return List.generate(
    count,
    (index) => {
      'title': '$topic Lesson ${index + 1}',
      'duration': 10 + index, // minutes
      'status': 'Locked', // initially locked - only unlocked after Start Course
    },
  );
}

final List<Course> allCourses = [
  Course(
    id: 1,
    title: 'Advanced React & Typescript',
    category: 'Web Development',
    icon: '💻',
    lessons: 12,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Alex Johnson',
    role: 'Senior Frontend Engineer',
    students: 50,
    duration: 18,
    reviews: 320,
    numStudents: 2400,
    description:
        'Master React 18 and TypeScript for building robust, scalable web applications with confidence.',
    totalTime: 12,
    lessonsList: mockLessons('React & TypeScript', 12),
    isSaved: false,
  ),
  Course(
    id: 2,
    title: 'Node.js API Development',
    category: 'Web Development',
    icon: '🧠',
    lessons: 18,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'James Miller',
    role: 'Backend Developer',
    students: 45,
    duration: 16,
    reviews: 250,
    numStudents: 1800,
    description: 'Build production-ready REST APIs using Node.js, Express, and MongoDB.',
    totalTime: 15,
    lessonsList: mockLessons('Node.js API', 18),
    isSaved: false,
  ),
  Course(
    id: 3,
    title: 'Mastering HTML, CSS & JS',
    category: 'Web Development',
    icon: '🌐',
    lessons: 25,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Linda White',
    role: 'UI Developer',
    students: 120,
    duration: 22,
    reviews: 410,
    numStudents: 5600,
    description: 'The ultimate front-end foundation course to master HTML, CSS, and JavaScript.',
    totalTime: 22,
    lessonsList: mockLessons('Frontend Basics', 25),
    isSaved: false,
  ),
  Course(
    id: 4,
    title: 'Next.js Fullstack Guide',
    category: 'Web Development',
    icon: '⚛️',
    lessons: 20,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'David Lee',
    role: 'Fullstack Engineer',
    students: 85,
    duration: 20,
    reviews: 310,
    numStudents: 2200,
    description: 'Build scalable and fast fullstack apps using Next.js, React, and APIs.',
    totalTime: 20,
    lessonsList: mockLessons('Next.js', 20),
    isSaved: false,
  ),
  Course(
    id: 5,
    title: 'Building RESTful APIs with Express',
    category: 'Web Development',
    icon: '🧩',
    lessons: 14,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Emma Brown',
    role: 'Software Engineer',
    students: 60,
    duration: 10,
    reviews: 190,
    numStudents: 1300,
    description:
        'Learn how to create powerful RESTful APIs using Express and integrate with modern frontends.',
    totalTime: 10,
    lessonsList: mockLessons('Express API', 14),
    isSaved: false,
  ),
  Course(
    id: 6,
    title: 'Tailwind CSS Deep Dive',
    category: 'Web Development',
    icon: '💠',
    lessons: 10,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Sophia Green',
    role: 'Frontend Designer',
    students: 40,
    duration: 6,
    reviews: 120,
    numStudents: 800,
    description:
        'Unlock the full potential of Tailwind CSS for responsive and elegant UI development.',
    totalTime: 6,
    lessonsList: mockLessons('Tailwind CSS', 10),
    isSaved: false,
  ),
  Course(
    id: 7,
    title: 'Vue.js 3 Masterclass',
    category: 'Web Development',
    icon: '🖥️',
    lessons: 22,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Lucas Turner',
    role: 'Frontend Engineer',
    students: 95,
    duration: 17,
    reviews: 300,
    numStudents: 1700,
    description:
        'Master Vue.js 3 with Composition API, state management, and scalable component design.',
    totalTime: 17,
    lessonsList: mockLessons('Vue.js', 22),
    isSaved: false,
  ),
  Course(
    id: 8,
    title: 'GraphQL & Apollo Fundamentals',
    category: 'Web Development',
    icon: '🔗',
    lessons: 15,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Olivia Martin',
    role: 'Software Architect',
    students: 70,
    duration: 13,
    reviews: 210,
    numStudents: 1500,
    description:
        'Learn how to design and consume GraphQL APIs using Apollo Client and Server.',
    totalTime: 13,
    lessonsList: mockLessons('GraphQL', 15),
    isSaved: false,
  ),
  Course(
    id: 9,
    title: 'Web Accessibility (A11Y) Essentials',
    category: 'Web Development',
    icon: '♿',
    lessons: 8,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Noah Wright',
    role: 'Accessibility Advocate',
    students: 30,
    duration: 5,
    reviews: 75,
    numStudents: 500,
    description:
        'Ensure your websites are accessible to all users by mastering A11Y best practices.',
    totalTime: 5,
    lessonsList: mockLessons('Accessibility', 8),
    isSaved: false,
  ),
  Course(
    id: 10,
    title: 'SEO Optimization for Developers',
    category: 'Web Development',
    icon: '🚀',
    lessons: 9,
    rating: 4.5,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Mia Carter',
    role: 'Digital Marketer',
    students: 55,
    duration: 8,
    reviews: 160,
    numStudents: 950,
    description:
        'Improve your website visibility and performance with developer-focused SEO techniques.',
    totalTime: 8,
    lessonsList: mockLessons('SEO', 9),
    isSaved: false,
  ),

  // DESIGN (11-20)
  Course(
    id: 11,
    title: 'UI/UX Design Fundamentals',
    category: 'Design',
    icon: '🎨',
    lessons: 15,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Chloe Kim',
    role: 'Product Designer',
    students: 110,
    duration: 14,
    reviews: 270,
    numStudents: 2100,
    description:
        'Learn the principles of user interface and experience design with hands-on Figma projects.',
    totalTime: 14,
    lessonsList: mockLessons('UI/UX', 15),
    isSaved: false,
  ),
  Course(
    id: 12,
    title: 'Figma for Beginners',
    category: 'Design',
    icon: '🖌️',
    lessons: 10,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ethan Hall',
    role: 'Visual Designer',
    students: 65,
    duration: 8,
    reviews: 180,
    numStudents: 1300,
    description: 'Get started with Figma and learn how to create beautiful, responsive UI designs.',
    totalTime: 8,
    lessonsList: mockLessons('Figma', 10),
    isSaved: false,
  ),
  Course(
    id: 13,
    title: 'Design Systems in Practice',
    category: 'Design',
    icon: '🧱',
    lessons: 12,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Isabella Brown',
    role: 'Design System Lead',
    students: 75,
    duration: 10,
    reviews: 150,
    numStudents: 950,
    description: 'Build scalable and consistent design systems for modern web and mobile applications.',
    totalTime: 10,
    lessonsList: mockLessons('Design Systems', 12),
    isSaved: false,
  ),
  Course(
    id: 14,
    title: 'Color Theory & Composition',
    category: 'Design',
    icon: '🎨',
    lessons: 8,
    rating: 4.5,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Henry Collins',
    role: 'Creative Director',
    students: 35,
    duration: 5,
    reviews: 90,
    numStudents: 600,
    description: 'Master the use of color, contrast, and visual hierarchy to create stunning designs.',
    totalTime: 5,
    lessonsList: mockLessons('Color Theory', 8),
    isSaved: false,
  ),
  Course(
    id: 15,
    title: 'Typography Masterclass',
    category: 'Design',
    icon: '🔤',
    lessons: 10,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Grace Allen',
    role: 'Graphic Designer',
    students: 48,
    duration: 6,
    reviews: 100,
    numStudents: 700,
    description: 'Learn typography principles and best practices to elevate your design layouts.',
    totalTime: 6,
    lessonsList: mockLessons('Typography', 10),
    isSaved: false,
  ),
  Course(
    id: 16,
    title: 'Wireframing & Prototyping in Figma',
    category: 'Design',
    icon: '🧩',
    lessons: 14,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Daniel Young',
    role: 'Product Designer',
    students: 95,
    duration: 12,
    reviews: 190,
    numStudents: 1100,
    description: 'Learn to quickly wireframe and prototype with Figma for collaborative design projects.',
    totalTime: 12,
    lessonsList: mockLessons('Prototyping', 14),
    isSaved: false,
  ),
  Course(
    id: 17,
    title: 'Designing for Mobile Interfaces',
    category: 'Design',
    icon: '📱',
    lessons: 12,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ella Roberts',
    role: 'UI Designer',
    students: 52,
    duration: 9,
    reviews: 130,
    numStudents: 890,
    description: 'Optimize your designs for mobile experiences using responsive and adaptive layouts.',
    totalTime: 9,
    lessonsList: mockLessons('Mobile Design', 12),
    isSaved: false,
  ),
  Course(
    id: 18,
    title: 'UX Research & Testing',
    category: 'Design',
    icon: '🔍',
    lessons: 11,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Liam Scott',
    role: 'UX Researcher',
    students: 90,
    duration: 10,
    reviews: 200,
    numStudents: 1300,
    description: 'Master user research, interviews, and usability testing for informed design decisions.',
    totalTime: 10,
    lessonsList: mockLessons('UX Research', 11),
    isSaved: false,
  ),
  Course(
    id: 19,
    title: 'Design Portfolio Building',
    category: 'Design',
    icon: '📁',
    lessons: 9,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Zoe Walker',
    role: 'Art Director',
    students: 42,
    duration: 7,
    reviews: 100,
    numStudents: 750,
    description: 'Create a stunning design portfolio that highlights your strengths and attracts employers.',
    totalTime: 7,
    lessonsList: mockLessons('Portfolio', 9),
    isSaved: false,
  ),
  Course(
    id: 20,
    title: 'Advanced UI Animations',
    category: 'Design',
    icon: '🎞️',
    lessons: 13,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Noah Brooks',
    role: 'Motion Designer',
    students: 68,
    duration: 11,
    reviews: 160,
    numStudents: 1020,
    description: 'Add delightful motion and transitions to your interfaces using Figma and After Effects.',
    totalTime: 11,
    lessonsList: mockLessons('Animations', 13),
    isSaved: false,
  ),

  // MOBILE DEVELOPMENT (21-25)
  Course(
    id: 21,
    title: 'Flutter App Development Bootcamp',
    category: 'Mobile Development',
    icon: '📱',
    lessons: 20,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Sarah Parker',
    role: 'Mobile App Engineer',
    students: 95,
    duration: 18,
    reviews: 410,
    numStudents: 3200,
    description: 'Learn Flutter and Dart to build high-performance, cross-platform mobile apps for Android and iOS.',
    totalTime: 18,
    lessonsList: mockLessons('Flutter', 20),
    isSaved: false,
  ),
  Course(
    id: 22,
    title: 'Android Development with Kotlin',
    category: 'Mobile Development',
    icon: '🤖',
    lessons: 18,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Michael Reed',
    role: 'Android Developer',
    students: 80,
    duration: 16,
    reviews: 290,
    numStudents: 2100,
    description: 'Master Android app development using Kotlin, Android Studio, and modern Jetpack components.',
    totalTime: 16,
    lessonsList: mockLessons('Android Kotlin', 18),
    isSaved: false,
  ),
  Course(
    id: 23,
    title: 'iOS Development with SwiftUI',
    category: 'Mobile Development',
    icon: '🍎',
    lessons: 15,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ava Williams',
    role: 'iOS Developer',
    students: 70,
    duration: 14,
    reviews: 240,
    numStudents: 1800,
    description: 'Build modern iOS applications using SwiftUI and Apple’s latest frameworks for UI and navigation.',
    totalTime: 14,
    lessonsList: mockLessons('SwiftUI', 15),
    isSaved: false,
  ),
  Course(
    id: 24,
    title: 'React Native Masterclass',
    category: 'Mobile Development',
    icon: '⚛️',
    lessons: 17,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Oliver Scott',
    role: 'Fullstack Developer',
    students: 88,
    duration: 15,
    reviews: 280,
    numStudents: 2500,
    description: 'Develop stunning cross-platform apps using React Native and connect them with REST APIs.',
    totalTime: 15,
    lessonsList: mockLessons('React Native', 17),
    isSaved: false,
  ),
  Course(
    id: 25,
    title: 'Firebase for Mobile Apps',
    category: 'Mobile Development',
    icon: '🔥',
    lessons: 10,
    rating: 4.5,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Sophia Clark',
    role: 'Cloud Developer',
    students: 60,
    duration: 8,
    reviews: 150,
    numStudents: 1200,
    description: 'Integrate Firebase services like Authentication, Firestore, and Cloud Messaging into your mobile apps.',
    totalTime: 8,
    lessonsList: mockLessons('Firebase', 10),
    isSaved: false,
  ),

  // DATA SCIENCE (26-30)
  Course(
    id: 26,
    title: 'Python for Data Science',
    category: 'Data Science',
    icon: '🐍',
    lessons: 18,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Daniel Harris',
    role: 'Data Scientist',
    students: 120,
    duration: 16,
    reviews: 420,
    numStudents: 3100,
    description: 'Learn Python libraries like NumPy, Pandas, and Matplotlib for effective data analysis and visualization.',
    totalTime: 16,
    lessonsList: mockLessons('Python DS', 18),
    isSaved: false,
  ),
  Course(
    id: 27,
    title: 'Machine Learning A–Z',
    category: 'Data Science',
    icon: '🤖',
    lessons: 22,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Emily Davis',
    role: 'ML Engineer',
    students: 95,
    duration: 20,
    reviews: 380,
    numStudents: 2800,
    description: 'A comprehensive introduction to machine learning, covering supervised, unsupervised, and neural networks.',
    totalTime: 20,
    lessonsList: mockLessons('Machine Learning', 22),
    isSaved: false,
  ),
  Course(
    id: 28,
    title: 'Deep Learning with TensorFlow',
    category: 'Data Science',
    icon: '🧠',
    lessons: 16,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Lucas Bennett',
    role: 'AI Researcher',
    students: 80,
    duration: 14,
    reviews: 300,
    numStudents: 1900,
    description: 'Learn to build and train deep neural networks using TensorFlow and Keras.',
    totalTime: 14,
    lessonsList: mockLessons('TensorFlow', 16),
    isSaved: false,
  ),
  Course(
    id: 29,
    title: 'Data Visualization with Tableau',
    category: 'Data Science',
    icon: '📊',
    lessons: 12,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ava Parker',
    role: 'Data Analyst',
    students: 60,
    duration: 10,
    reviews: 200,
    numStudents: 1200,
    description: 'Create compelling dashboards and data visualizations using Tableau.',
    totalTime: 10,
    lessonsList: mockLessons('Tableau', 12),
    isSaved: false,
  ),
  Course(
    id: 30,
    title: 'SQL & Database Management',
    category: 'Data Science',
    icon: '🗄️',
    lessons: 14,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Mia Bennett',
    role: 'Database Developer',
    students: 70,
    duration: 12,
    reviews: 250,
    numStudents: 1500,
    description: 'Master SQL queries, database design, and management for effective data storage and retrieval.',
    totalTime: 12,
    lessonsList: mockLessons('SQL', 14),
    isSaved: false,
  ),

  // EXTRA (31-40)
  Course(
    id: 31,
    title: 'Cybersecurity Essentials',
    category: 'Web Development',
    icon: '🛡️',
    lessons: 10,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ethan Brooks',
    role: 'Security Analyst',
    students: 50,
    duration: 8,
    reviews: 150,
    numStudents: 900,
    description: 'Protect applications and networks with the fundamentals of cybersecurity.',
    totalTime: 8,
    lessonsList: mockLessons('Cybersecurity', 10),
    isSaved: false,
  ),
  Course(
    id: 32,
    title: 'Cloud Computing with AWS',
    category: 'Web Development',
    icon: '☁️',
    lessons: 14,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Olivia Bennett',
    role: 'Cloud Engineer',
    students: 60,
    duration: 12,
    reviews: 200,
    numStudents: 1300,
    description: 'Learn AWS services, architecture, and cloud deployment practices.',
    totalTime: 12,
    lessonsList: mockLessons('AWS Cloud', 14),
    isSaved: false,
  ),
  Course(
    id: 33,
    title: 'DevOps Fundamentals',
    category: 'Web Development',
    icon: '⚙️',
    lessons: 12,
    rating: 4.5,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Liam Foster',
    role: 'DevOps Engineer',
    students: 55,
    duration: 10,
    reviews: 160,
    numStudents: 1100,
    description: 'Understand CI/CD pipelines, Docker, and deployment strategies for modern development.',
    totalTime: 10,
    lessonsList: mockLessons('DevOps', 12),
    isSaved: false,
  ),
  Course(
    id: 34,
    title: 'Artificial Intelligence Overview',
    category: 'Data Science',
    icon: '🤖',
    lessons: 10,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Sophia Evans',
    role: 'AI Specialist',
    students: 45,
    duration: 8,
    reviews: 140,
    numStudents: 950,
    description: 'Explore AI concepts, applications, and ethics in modern technology.',
    totalTime: 8,
    lessonsList: mockLessons('AI Basics', 10),
    isSaved: false,
  ),
  Course(
    id: 35,
    title: 'Blockchain Essentials',
    category: 'Web Development',
    icon: '⛓️',
    lessons: 8,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Noah Adams',
    role: 'Blockchain Developer',
    students: 35,
    duration: 6,
    reviews: 120,
    numStudents: 800,
    description: 'Learn the foundations of blockchain, smart contracts, and decentralized apps.',
    totalTime: 6,
    lessonsList: mockLessons('Blockchain', 8),
    isSaved: false,
  ),
  Course(
    id: 36,
    title: 'Game Development with Unity',
    category: 'Mobile Development',
    icon: '🎮',
    lessons: 18,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Lucas Hill',
    role: 'Game Developer',
    students: 70,
    duration: 16,
    reviews: 250,
    numStudents: 2000,
    description: 'Build engaging 2D and 3D games with Unity and C# programming.',
    totalTime: 16,
    lessonsList: mockLessons('Unity', 18),
    isSaved: false,
  ),
  Course(
    id: 37,
    title: 'Augmented Reality Development',
    category: 'Mobile Development',
    icon: '🕶️',
    lessons: 12,
    rating: 4.7,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Emma Wilson',
    role: 'AR Developer',
    students: 50,
    duration: 10,
    reviews: 180,
    numStudents: 1200,
    description: 'Learn ARKit and ARCore to create immersive augmented reality experiences.',
    totalTime: 10,
    lessonsList: mockLessons('AR Development', 12),
    isSaved: false,
  ),
  Course(
    id: 38,
    title: 'Big Data Analytics',
    category: 'Data Science',
    icon: '📈',
    lessons: 15,
    rating: 4.8,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Mia Johnson',
    role: 'Data Engineer',
    students: 85,
    duration: 14,
    reviews: 300,
    numStudents: 2100,
    description: 'Process and analyze large datasets using Hadoop, Spark, and cloud solutions.',
    totalTime: 14,
    lessonsList: mockLessons('Big Data', 15),
    isSaved: false,
  ),
  Course(
    id: 39,
    title: 'Ethical Hacking Fundamentals',
    category: 'Web Development',
    icon: '🕵️‍♂️',
    lessons: 10,
    rating: 4.6,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Ethan Green',
    role: 'Security Analyst',
    students: 55,
    duration: 8,
    reviews: 160,
    numStudents: 1000,
    description: 'Learn penetration testing and ethical hacking techniques to secure applications.',
    totalTime: 8,
    lessonsList: mockLessons('Ethical Hacking', 10),
    isSaved: false,
  ),
  Course(
    id: 40,
    title: 'Data Science Capstone Project',
    category: 'Data Science',
    icon: '🎯',
    lessons: 20,
    rating: 4.9,
    progress: 0.0,
    status: 'Not Started',
    instructor: 'Sophia Taylor',
    role: 'Data Scientist',
    students: 100,
    duration: 18,
    reviews: 400,
    numStudents: 2800,
    description:
        'Apply your data science skills in a real-world project covering end-to-end analysis, visualization, and modeling.',
    totalTime: 18,
    lessonsList: mockLessons('Capstone Project', 20),
    isSaved: false,
  ),
];
